# themes:
# mkdir -p ~/.config/alacritty/themes
#Â git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
general.import = [
	"~/.config/alacritty/themes/themes/xterm.toml"
	# "~/.config/alacritty/themes/themes/hyper.toml"
	# "~/.config/alacritty/themes/themes/alabaster_dark.toml"
	# "~/.config/alacritty/themes/themes/campbell.toml"
	# "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
]

[font]
normal = { family = "FiraMono Nerd Font Mono", style = "Regular" }
size = 12.0

[mouse]
hide_when_typing = true

[window]
decorations = "None"
